### ISSUE TITLE
Drawer Closing Issue

### ISSUE THREAD

**Issue by Sadat-Hossain-01** [risenfromashes/harmony-web#11]
When the drawers are closed using the close button, for some reason, the controlling button does not immediately open it on the next click. It has to be clicked twice to open the drawer again. Although the other behaviors of drawer closing are just fine (i.e. click outside and other things like that). Need to fix this.

**Comment by SadatHossain999** [comment]
fixed by adding bind:open={draweropee}. The binding should be there to make sure the change in the drawer comopnent is reflected in the outer calling one's variable

**Comment by Sadat-Hossain-01** [comment]
fixed in commit f50d0dda0ce70f5c4828bab63896adf694e56a05
