### ISSUE TITLE
Add drawers to the events

### ISSUE THREAD

**Issue by SadatHossain999** [risenfromashes/harmony-web#6]
In the events page, on clicking an event, a drawer should be opened from the right side and it should contain the description of the respective event. Also, fix the formatting of the events, they should ideally show the ending date only and font sizes need to be fixed as well.

**Comment by Sadat-Hossain-01** [comment]
Decided to not to do the event detail drawer thing as all the information is shown in detail anyway, and other things of event page formatted properly. New event drawer added though in commit bd3a384d39d79b6fb3c67504257a86e7c4810765
