### ISSUE TITLE
Fix the issues created while routing to a different page keeping things open in one page

### ISSUE THREAD

**Issue by SadatHossain999** [risenfromashes/harmony-web#9]
Say, if one or more of the accordions are open, and we go to a different page, then the accordion closing and that page appearing happens simultaneously. Because of that, the screen for some moment shows them both, this has to be fixed. 
Try with onDestroy() handler maybe.

**Comment by Sadat-Hossain-01** [comment]
715e7a7aae56ca259c2bc22468b812b050740ee5
